### ISSUE TITLE
Unable to migrate redmine_vote v0.0.3 in Redmine 2.3.0

### ISSUE THREAD

**Issue by codemonkee** [ande3577/redmine_vote#14]
First attempt at installing
git cloned into plug-ins directory
Ran migration, hangs on CalculateInitialVotesValue: migrating

```
bash-3.2$ rake redmine:plugins:migrate RAILS_ENV=production
Migrating redmine_charts2 (Redmine Charts)...
Migrating redmine_didyoumean (Did You Mean?)...
Migrating redmine_issue_templates (Redmine Issue Templates plugin)...
Migrating redmine_vote (Redmine Vote plugin)...
==  VotesTableCreate: migrating     ===============================================
-- create_table(:votes, {:force=>true})
   -> 0.0921s
-- add_index(:votes, [:user_id], {:name=>"fk_votes_user"})
   -> 0.0433s
-- add_index(:votes, [:voteable_id, :voteable_type], {:name=>"fk_votes_voteable"})
   -> 0.0425s
==  VotesTableCreate: migrated (0.1789s)     ======================================

==  IssuesAddVotesValue: migrating     ============================================
-- add_column(:issues, :votes_value, :integer, {:default=>0, :null=>false})
   -> 0.3277s
==  IssuesAddVotesValue: migrated (0.3280s)     ===================================

==  CalculateInitialVotesValue: migrating     =====================================
```

**Redmine Information:**

```
Environment:
  Redmine version                          2.3.0.stable
  Ruby version                             1.9.3 (i686-linux)
  Rails version                            3.2.13
  Environment                              production
  Database adapter                         Mysql2
Redmine plugins:
  redmine_charts2                          0.2.1
  redmine_didyoumean                       1.2.0
  redmine_issue_templates                  0.0.5
  redmine_vote                             0.0.3
```

**Comment by ande3577** [comment]
How many issues do you have on the redmine instance?  For large sets it can
take some time.  I'll work on speeding it up.

On Mon, Apr 29, 2013 at 6:30 PM, Tim notifications@github.com wrote:

> First attempt at installing
> git cloned into plug-ins directory
> Ran migration, hangs on CalculateInitialVotesValue: migrating
> 
> bash-3.2$ rake redmine:plugins:migrate RAILS_ENV=production
> Migrating redmine_charts2 (Redmine Charts)...
> Migrating redmine_didyoumean (Did You Mean?)...
> Migrating redmine_issue_templates (Redmine Issue Templates plugin)...
> Migrating redmine_vote (Redmine Vote plugin)...
> ==  VotesTableCreate: migrating     ===============================================
> -- create_table(:votes, {:force=>true})
>    -> 0.0921s
> -- add_index(:votes, [:user_id], {:name=>"fk_votes_user"})
>    -> 0.0433s
> -- add_index(:votes, [:voteable_id, :voteable_type], {:name=>"fk_votes_voteable"})
>    -> 0.0425s
> ==  VotesTableCreate: migrated (0.1789s)     ======================================
> 
> ==  IssuesAddVotesValue: migrating     ============================================
> -- add_column(:issues, :votes_value, :integer, {:default=>0, :null=>false})
>    -> 0.3277s
> ==  IssuesAddVotesValue: migrated (0.3280s)     ===================================
> 
> ==  CalculateInitialVotesValue: migrating     =====================================
> 
> _Redmine Information:_
> 
> Environment:
>   Redmine version                          2.3.0.stable
>   Ruby version                             1.9.3 (i686-linux)
>   Rails version                            3.2.13
>   Environment                              production
>   Database adapter                         Mysql2
> Redmine plugins:
>   redmine_charts2                          0.2.1
>   redmine_didyoumean                       1.2.0
>   redmine_issue_templates                  0.0.5
>   redmine_vote                             0.0.3
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ande3577/redmine_vote/issues/14
> .

## 

David Anderson

**Comment by codemonkee** [comment]
Just under 1600 issues.
