### ISSUE TITLE
Support Question: Usage?

### ISSUE THREAD

**Issue by codemonkee** [ande3577/redmine_vote#17]
After added the appropriate permissions to each role and adding the module to a project, I can vote up/down from the issues context menu.

```
Started POST "/redmine/vote/up?id=1599" for 10.10.1.49 at 2013-05-04 16:44:09 -0700
Processing by VoteController#up as HTML
  Parameters: {"authenticity_token"=>"sCXruIIfpf/0UPycYjWihBvm76VhLUI1K8jbYQtrsek=", "id"=>"1599"}
  Current user: twhitehead (id=6)
```

However opening up an issue and clicking on the Up / Down arrow does not invoke anything, No errors received in the browser and no action shown in the redmine log.

Once a vote is added from the context menu, a delete icon appears in an open ticket - which calls vote/clear?id= and works without issue.

```
Started DELETE "/redmine/vote/clear?id=1599" for 127.0.0.1 at 2013-05-04 16:46:55 -0700
Processing by VoteController#clear as HTML
  Parameters: {"authenticity_token"=>"sCXruIIfpf/0UPycYjWihBvm76VhLUI1K8jbYQtrsek=", "id"=>"1599"}
  Current user: twhitehead (id=6)
```

Is there a setting that I am missing that needs to be enabled?

**Redmine Information:**

```
Environment:
  Redmine version                          2.3.0.stable
  Ruby version                             1.9.3 (i686-linux)
  Rails version                            3.2.13
  Environment                              production
  Database adapter                         Mysql2
Redmine plugins:
  redmine_charts2                          0.2.1
  redmine_didyoumean                       1.2.0
  redmine_issue_templates                  0.0.5
  redmine_vote                             0.0.3 - commit 3d1576b
```

**Comment by ande3577** [comment]
After voting.  The votes count and votes percent columns will be updated.
From the context menu,  this may not be apparent unless I've of these
columns is being displayed.  There will be a flash message indicating that
the vote was successful.

**Comment by codemonkee** [comment]
Nothing occurs when I click the upvote or downvote icons; however, the clear icon invokes the clear function, looking at the production.log no request is sent, I have tried this in 2 browsers.

```
IE10 v10.0.9200.16540
Firefox v20.0.1
```

I just installed Chrome on this machine and interesting enough Chrome does prompt me to re-authenticate on the server, although it is still failing.

I'll take a look at my main Apache logs and see what I can find. I find it interesting that the up/down fails but clear works and up/down from the context menu also works.

**Comment by ande3577** [comment]
Do you have javascript blocked perchance?  as voting from the issue page is
invoked via javascript.

On Mon, May 6, 2013 at 9:08 AM, Tim notifications@github.com wrote:

> Nothing occurs when I click the upvote or downvote icons; however, the
> clear icon invokes the clear function, looking at the production.log no
> request is sent, I have tried this in 2 browsers.
> 
> IE10 v10.0.9200.16540
> Firefox v20.0.1
> 
> I just installed Chrome on this machine and interesting enough Chrome does
> prompt me to re-authenticate on the server, although it is still failing.
> 
> I'll take a look at my main Apache logs and see what I can find. I find it
> interesting that the up/down fails but clear works and up/down from the
> context menu also works.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ande3577/redmine_vote/issues/17#issuecomment-17483453
> .

## 

David Anderson

**Comment by codemonkee** [comment]
No, javascript is enabled on all browsers.

Using the context menu - calling `https://kenny/redmine/vote/up?id=1600`

```
192.168.0.200 - - [06/May/2013:07:32:19 -0700] "POST /redmine/vote/up?id=1600 HTTP/1.1" 302 108
192.168.0.200 - - [06/May/2013:07:32:19 -0700] "POST /redmine/vote/up?id=1600 HTTP/1.1" 302 108 "https://kenny/redmine/projects/test/issues"
192.168.0.200 - - [06/May/2013:07:32:20 -0700] "GET /redmine/projects/test/issues HTTP/1.1" 200 29191
192.168.0.200 - - [06/May/2013:07:32:20 -0700] "GET /redmine/projects/test/issues HTTP/1.1" 200 29191 "https://kenny/redmine/projects/test/issues"
```

Using the vote up botton on an issue - calling `https://kenny/vote/up.js?id=1600&count=1`

```
192.168.0.200 - twhitehead@SJRB.AD [06/May/2013:07:20:35 -0700] "POST /vote/up.js?id=1600&count=1 HTTP/1.1" 404 332
192.168.0.200 - twhitehead@SJRB.AD [06/May/2013:07:20:35 -0700] "POST /vote/up.js?id=1600&count=1 HTTP/1.1" 404 332 "https://kenny/redmine/issues/1600"
[Mon May 06 07:20:36 2013] [error] [client 192.168.0.200] File does not exist: /var/www/html/vote, referer: https://kenny/redmine/issues/1600
```

`vote(direction)` is calling a root path on [Line 3 of votes.js](https://github.com/ande3577/redmine_vote/blob/master/assets/javascripts/votes.js#L3)

It then gives a 404 - calling `https://kenny/redmine/issues/vote/up.js?id=1600&count=1`

```
192.168.0.200 - - [06/May/2013:07:34:30 -0700] "POST /redmine/issues/vote/up.js?id=1600&count=1 HTTP/1.1" 404 485
192.168.0.200 - - [06/May/2013:07:34:30 -0700] "POST /redmine/issues/vote/up.js?id=1600&count=1 HTTP/1.1" 404 485 "https://kenny/redmine/issues/1600"
```

The clear button works - calling `https://kenny/redmine/vote/clear?id=1600`

```
192.168.0.200 - - [06/May/2013:07:34:57 -0700] "POST /redmine/vote/clear?id=1600 HTTP/1.1" 302 99
192.168.0.200 - - [06/May/2013:07:34:57 -0700] "POST /redmine/vote/clear?id=1600 HTTP/1.1" 302 99 "https://kenny/redmine/issues/1600"
192.168.0.200 - - [06/May/2013:07:34:57 -0700] "GET /redmine/issues/1600 HTTP/1.1" 200 31489
192.168.0.200 - - [06/May/2013:07:34:57 -0700] "GET /redmine/issues/1600 HTTP/1.1" 200 31489 "https://kenny/redmine/issues/1600"
```

I am just busy with a few others things at the moment, so I haven't looked to see what the difference is between a vote up/down and the clear call.

**Comment by ande3577** [comment]
Apologies for not getting to this sooner as the last week has been a little hectic. The link was malformed in the javascript.  See if this solves the problem.
